### PR TITLE
History of cultures

### PR DESCRIPTION
**Pull request by LT-Rascek**
~~Splitting #36 as it currently CTDs and split is a logical one.~~ This branch also fixes all the culture window display bugs with suggested culture era portraits.

### CODE REVIEW

**Comment by loup99** [comment]
Does this branch CTD?

**Comment by LT-Rascek** [comment]
It does not CTD for me. Does it cause any problems for you?

**Comment by loup99** [comment]
> It does not CTD for me. Does it cause any problems for you?

No, I was asking since you were referring to a CTD in a previous branch. I haven't tested this one.

**Comment by loup99** [comment]
For your information, this branch now conflicts with master.

**Comment by LT-Rascek** [comment]
> For your information, this branch now conflicts with master.

Yeah, I would expect that in general; it was conflicts with `BP/history/_BP_notes.info`; rebased and force-pushed the necessary fixes.

**Review by loup99 — APPROVED** [review]

**Pull request merged**
