### PR TITLE
Draft Mazdan Family Implementation

### PR DESCRIPTION
**Pull request by LT-Rascek**
Adds Zoroastrian, Dualist, and Hepthalite faiths to game under rf_mazdan banner.

Based on what I've read, there should be an "ecumenical"-type doctrine for at least some of the Zoroastrian faiths, since they (Zurvanism,Uratism) more-or-less had state sanction while others didn't have it or had it and lost it (Mazdakism). I've created the "Approved Cult" doctrine to handle those cases. We'll probably want an event chain relating to Mazdakism, since it went from state support to persecution in the early Sixth Century.

Remaining to-dos:
* Add Mazdan syncretism and related doctrines/tenets
* Review Dualist deity names to make certain they match well WtWSMS

And a "nice-to" but not a strictly required element:
* Specific Mazdan graphics set instead of leaning on the Eastern graphics set; graphics (besides simple ones) are a bit outside my wheelhouse though.

### CODE REVIEW

**Comment by herkles** [comment]
Question: Should Mithraism be in the Mazdan family or in the Pagan family? If it is in the pagan family, should have Mazdan sympathy? 

Instead of Approved Cult what about the term Ašavan which according to wiki has a number of meanings but also includes: denote any follower of the "Good Religion." So it has a more Zoroastrian term?

**Comment by LT-Rascek** [comment]
> Question: Should Mithraism be in the Mazdan family or in the Pagan family? If it is in the pagan family, should have Mazdan sympathy?

From what I've seen, while it borrows from the Perisan Mithra, it made a number of new innovations that'd make it Hellenic. Maybe having Mazdan syncretism, but I'm not certain if it was similar enough for that.

> Instead of Approved Cult what about the term Ašavan which according to wiki has a number of meanings but also includes: denote any follower of the "Good Religion." So it has a more Zoroastrian term?

Made those changes to the localization and upgraded the effect from "Astray" to "Righteous", since Zurvanism and Zoroastrianism had that sort of relationship until the Islamic conquest.

**Comment by LT-Rascek** [comment]
As an aside note, we should probably separate out the binary graphics files from the rest of the repo, since git and graphics binaries do not work well on the whole (small changes in presentation can yield large changes in the resulting file). A few solutions are suggested in this stackoverflow thread:

https://stackoverflow.com/questions/4697216/is-git-good-with-binary-files

**Comment by loup99** [comment]
> As an aside note, we should probably separate out the binary graphics files from the rest of the repo, since git and graphics binaries do not work well on the whole (small changes in presentation can yield large changes in the resulting file). A few solutions are suggested in this stackoverflow thread:
> 
> https://stackoverflow.com/questions/4697216/is-git-good-with-binary-files

I use Git LFS myself, does that seem like a viable option for you too?

**Comment by LT-Rascek** [comment]
> I use Git LFS myself, does that seem like a viable option for you too?

I have no strong preference; it's just something we should settle upon before adding a large number of graphics items (e.g., religious icons for all the Christian denominations, &c.)

**Comment by LT-Rascek** [comment]
Rebased onto bdb067e. Should be ready for merge

**Comment by loup99** [comment]
> > I use Git LFS myself, does that seem like a viable option for you too?
> 
> I have no strong preference; it's just something we should settle upon before adding a large number of graphics items (e.g., religious icons for all the Christian denominations, &c.)

Unless there is any objections I propose that we settle on Git LFS in that case. I have a preference for that since I used it in the past.

**Review by loup99 — APPROVED** [review]
I don't have any objections, I think it can be merged. Some details might be tweaked later on as we test and modify, but for now the core can be merged.

**Pull request merged**
