### PR TITLE
Map tweaks

### PR DESCRIPTION
**Pull request by LT-Rascek**
Started looking at mapping landed titles from WtWSMS to CK3 map. First step is tweaking some county borders to make the Rhine, Loire, and Danube county borders. All county names are temporary and will have to do further modification and holding tweaks.

Temporary map showing counties that were tweaked (with hot pink boxes) along the Loire, Danube, and Rhine.
kingdoms

Actual kingdom modifications are very much a moving target and I'm just trying to map WtWSMS landed kingdoms to CK3 right now. I think some will need to be rethought/revisited like Cilicia, Galatia, Iberia/Abkhazia, Armenia, and Tripolitania. Basing mappings heavily on [this map](https://upload.wikimedia.org/wikipedia/commons/0/04/The_Roman_Empire_ca_400_AD.png) right now (finding city/CK3 barony correspondences and the like, just as was done on #2).

Edit: 3b3e9ed snuck in there and might cause a conflict. I'll need to revert that later.

### CODE REVIEW

**Comment by AvalonXD** [comment]
FYI that province map is old now with the Northern Lords update.

**Comment by LT-Rascek** [comment]
> FYI that province map is old now with the Northern Lords update.

Yes, but the new counties are in Iceland (and a few additional _baronies_ in Scotland), so the map is still useable from what I can glean. I don't think we're doing anything exotic with Iceland.

**Comment by loup99** [comment]
Is there any specific help you need?

**Comment by LT-Rascek** [comment]
>Is there any specific help you need?

I don't need any specific help _per se_; I just want to make sure we're in agreement that the Danube, Rhine, Elbe, Visutula, &c. should be the dividing line between counties instead of having counties straddling the river borders.

> Do you want a map of settlements and names in the Roman Empire to find baronies to add? Like the Digital Atlas of the Roman Empire of Johan Åhlfeldt from the University of Gothenburg? https://imperium.ahlfeldt.se/

**_That is perfect_** for figuring out how to implement roman cultural names for baronies! Thank you.

**Comment by loup99** [comment]
> **_That is perfect_** for figuring out how to implement roman cultural names for baronies! Thank you.

Note that we already have very extensive cultural titles for baronnies in CK2 that can be copied and pasted.

**Comment by LT-Rascek** [comment]
> Yes, the Romans liked having their borders centred on rivers, so I think it makes sense in those areas to retain those limits, even if Germanic or Romano-Germanic rulers didn't necessarily follow it exactly.

Okay, I'll probably merge this work in with #27 in the near future then.

> Note that we already have very extensive cultural names for baronnies in CK2 that can be copied and pasted.

I noticed that _after_ I had pretty much finished doing the WRE and ERE first cut... _sigh_

**Comment by loup99** [comment]
> I noticed that after I had pretty much finished doing the WRE and ERE first cut... sigh

Sorry to hear that, but the thing is that some of the names we have are reconstructed to fill in holes for Greek/Latin and based upon archeological data so I think it would really be better to use that as a base.

**Comment by LT-Rascek** [comment]
Newer branch overtakes this work, so closing.

**Pull request closed without merging**
