### PR TITLE
Compressed version of titles_history_refactor

### PR DESCRIPTION
**Pull request by LT-Rascek**
@loup99, @kai229
Branch got long, so I've compressed it for easier switching
Stopped at 52337c6 commit (Fix British history bugs)

Independent Realms:
independent_realms

Processing Map:
processing_map

### CODE REVIEW

**Comment by LT-Rascek** [comment]
Implemented e_scandinavia, including k_iceland. Also removed Odoacer's land in k_annonaria.

Independent Realms:
independent_realms

Processing Map:
processing_map

**Comment by loup99** [comment]
There is a typo, BP/history/titles/bp_k_galaicia-volhynia.txt -> BP_k_galicia_volhynia.txt

**Comment by LT-Rascek** [comment]
5a3dae8 completes e_russia.

One of the groups I added are the Meshchera, a historical volga-finnic ethnic group that lived in the Ryazan region during the period.

So county culture/religions were added to Slavic to separate the east and west galindians like in WtWSMS.

Moving forward, the Vladmir duchy, and slavic rostov duchies will be removed as the Volga Finns lived in the region at the time. The Muromian Volga-Finnic culture will replace the slavic muromians from WtWSMS.

Independent Realms:
independent_realms

Processing Map:
processing_map

**Comment by LT-Rascek** [comment]
Completed e_finland. Did some quick fill in in various regions where I didn't want an empty history for testing purposes (pink provinces).

I plan to do more detail in the Horn of Africa at a later date.

I think it's ready for integration Most of the WtWSMS has been mapping outside of missing regions (e_tibet,e_kanem_bornu,e_guinea) or distorted regions (e_mongolia, e_mali,e_siberia).

Independent Realms:
independent_realms

Processing Map:
processing_map

Legend:
Dark Green: Direct mapping from WtWSMS
Lighter Green: Indirect mapping from WtWSMS
Lightest Green: Some estimation I did, but should be acceptable.
Yellow: I changed something from WtWSMS, but it shouldn't be controversial
Orange: I changed something from WtWMS, it might be controversial
Gold: Provinces that will almost certainly create issues for later bookmarks (Mogyar and Bashkir provinces)
Light Blue: Provinces that I added cultural-related titles (like the Mordvins), that weren't necessarily from WtWMS or saw some character changes to make them conformal with CK3.
Pink - Various provinces I mapped to current or new titles for convenience sake.
Brown - Regions with empty histories that I don't think will be a testing issue.

**Comment by loup99** [comment]
Tibet and Nepal are more or less mapped for CK2. It can be adjusted if there is feedback, but we have a rough setup. In Mali the indirect mapping should work as it did elsewhere, I believe. However, for Kanem Bornu and Guinea as well as eastern Mongolia and Siberia research will have to be done.

**Comment by loup99** [comment]
- You have both the kingdom of the Garamantes and the balkanised duchies
- Sahara is composed of isolated non-contiguous pockets, it is unplayable and not plausible, I would divide it in three for the respective corridors, unless we intend to add provinces to bridge between the corridors.
- I don't think Madeira was inhabited prior to Portuguese colonisation?
- The Guptas are called Rajastan, we should change that to be the dynasty name instead

**Comment by LT-Rascek** [comment]
> How do flags work in CK3? How should we proceed to port those from CK2?

I should have left the flags in the history, although commented out. I imagine some would not be necessary any longer.

Example from Vanilla CK3 k_aragon:

```
1035.10.18 = {
		holder = 110510 # Ramiro I Jimena
		
		# Cannot be re-formed by decision.
		effect = {
			add_to_global_variable_list = {
				name = unavailable_unique_decisions
				target = flag:flag_formed_kingdom_of_aragon
			}
		}
	}
```

> I don't think Madeira was inhabited prior to Portuguese colonisation?

I don't think it was, but I'm not sure how to represent that. Best guess is we can remove Madeira when it's time to revamp the map at a deeper level (e.g., adding things to the African desert for various tribes).

> Due to missing cultural title localisation and map changes Sala Colonia seems to have moved northwards?

Correct; more precisely, it is in province 4700 Sala, which matches its actual location.

>The Guptas are called Rajastan, we should change that to be the dynasty name instead
> Same with the Zhunbils who are Kabulistan
> Himyar and Azd 'Uman have become Yemen and Oman

I think these are handled at the culture level; I'll review and let you know.

**Comment by loup99** [comment]
> I should have left the flags in the history, although commented out. I imagine some would not be necessary any longer.

I didn't express myself clearly enough. Title flags are a pertinent remark, but I meant coats of arms as in actual flags visible on the map. :wink:

> I don't think it was, but I'm not sure how to represent that. Best guess is we can remove Madeira when it's time to revamp the map at a deeper level (e.g., adding things to the African desert for various tribes).

Isn't it possible to treat it as a wasteland for now? What happens if you remove the Madeira province history and title history? Does it still auto-generate a ruler? In CK2 it was possible to have a province unplayable if it neither had title and province history. Although of course here it is very minor, only one isolated island. 

> Correct; more precisely, it is in province 4700 Sala, which matches its actual location.
> 
> Guptas are currently akan culture, so that is expected (we haven't remapped sanskrit yet).
> 
> I think these are handled at the culture level; I'll review and let you know.
> 
> I'll revisit fixing Africa this week.

Ok.

> I found the jade dragon branch and will revisit that area this week. Are Sakka and Sakkan supposed to be different cultures?

It is not entirely finished, so still work in progress, but we discussed how to map [it in the issue](https://github.com/loup99/WtWSMS/issues/397) and [there is a drive](https://docs.google.com/document/d/1L-kgkYwldE3HOYRb_Mpv1Sz2-NJu8PVMUdKYjXA7y3A/edit?usp=sharing). Sakka and Sakkan should be the same, that is an oversight.

**Comment by LT-Rascek** [comment]
> I didn't express myself clearly enough. Title flags are a pertinent remark, but I meant coats of arms as in actual flags visible on the map. 😉

Ah, I haven't done anything with those because:
* They are binary files; wasn't sure if we want to push a bunch of binary files to this repo or a different, better repo for binary data files
* As you can see from my attempts at art elsewhere, it's not something I can do very well.

> Isn't it possible to treat it as a wasteland for now? What happens if you remove the Madeira province history and title history? Does it still auto-generate a ruler? In CK2 it was possible to have a province unplayable if it neither had title and province history. Although of course here it is very minor, only one isolated island.

I'll look into it and see what I can do.

> It is not entirely finished, so still work in progress, but we discussed how to map it in the issue and there is a drive. Sakka and Sakkan should be the same, that is an oversight.

Yep, I can use that branch; I just needed to make sure I wasn't missing something important with the Sakka/Sakkan issue.

**Comment by loup99** [comment]
> They are binary files; wasn't sure if we want to push a bunch of binary files to this repo or a different, better repo for binary data files

They are binary files but they are not heavy and we want to have everything in one place. 

> As you can see from my attempts at art elsewhere, it's not something I can do very well.

We have all the existing flags, although apparently it is all script now?

**Comment by LT-Rascek** [comment]
> They are binary files but they are not heavy and we want to have everything in one place.

Alright, I'll see what I can do on that when the map is more settled.

=====
Spent some time on West Africa trying to map things. Very little maps well so I had to do a lot of estimation or creation of hypothetical rulers for various places. But the new history reaches about as far south as WtWSMS did. Also added a legendary ruler of Ghana, Dinga, based on oral traditions of the region as the founder of Ghana (which is ruled by char 88 in 476). We should probably have a "legendary" trait for some of these characters as well, just as a historical note for players who dig through the title history.

=====

I took some time and, based on the mazedist, zurvanist, siyavashist traits, fixed the character religion histories not mapping correctly for Zoroastrianism (by adding Siyavashism as a Zoroastrian faith and then mapping based on the traits). I suspect making the Parthians Zurvanists is incorrect (in that they were probably more orthodox Mazdayasna while the Sassanids were more Zurvanist than not), but I need to read "Some Reflections on Zurvanism" for more details.

Also, as Chuyue is no longer a culture, I've mapped Chuyue characters to Xiongnu.

**Review by loup99 — APPROVED** [review]

**Pull request merged**
