### PR TITLE
Henotikon Implementation

### PR DESCRIPTION
**Pull request by LT-Rascek**
Putting Nicene Mechanics work here.

Mostly implemented the Henotikon; have not created the option to impose it on all of the Nicene Church.
Will also put Ecumenical Council Mechanics here; development is closely related to the Henotikon implementation.

Will probably revise the Apostolic, Coptic, Georgian, and Nicene tenets/doctrines in light of successful Council Mechanics (the Apostolic/Coptic/Georgian churches should probably start with the Universal Church mechanic and gradually loose it as further councils refine Orthodoxy).

### CODE REVIEW

**Comment by LT-Rascek** [comment]
Issuing Henotikon Decision
_00_issuing_henotkon_decision

Issuing Henotikon Event
_01_issuing_henotikon_event

Henotikon County Opinion
_02_henotikon_county_opinion

Henotikon Vassal Opinion
_03_henotokon_vassal_opinion

Henotikon Revoke Decision
_04_revoke_henotikon_decision

Henotikon Revoke Event
_05_revoke_henotikon_event

**Comment by LT-Rascek** [comment]
Still finding some bugs with the current implementation and need to work out mechanics to force Henotikon on all of Nicene Christiandom, but the events and decisions are mostly mapped out now.

After bugfixes, need to build upon this work to get Ecumenical Council mechanics implemented as well.

**Comment by loup99** [comment]
Tell me when you feel satisfied with progress so that this can be reviewed. 😃

**Comment by LT-Rascek** [comment]
I'll need to rebase this and focus on wrapping up the Henotikon and see if the Hotfixes broke any of my code.

**Comment by loup99** [comment]
> 
> 
> I'll need to rebase this and focus on wrapping up the Henotikon and see if the Hotfixes broke any of my code.

Ok 👍

**Comment by LT-Rascek** [comment]
Rebasing went fine; reviewing my old code, I didn't like the implementation (relied far too heavily on yearly events which I think was likely to cause issues down the line). Did a partial refactor. 

Henotikon issuance now appends a doctrine to ecumenical Christian faiths that chips away at fervor in proportion to holy sites (essentially opposite of Pentarchy), along with creating two traits:

embraced_henotikon
* +5 popular opinion (can't restrict to just specific faith provinces unfortunately)
* +10 same opinion, -5 opposite opinion

repudiated_henotikon
* +1 piety/month
* +5 same opinion, -10 opposite opinion
* Trying to make it so there's a bigger negative opinion of embraced_henotikon for clergy members

Very similar impact to previous code, but much easier to write this time around. Net effect of this, code wise, is a slightly more involved front end (user interface, decisions, events) for a much more simplified back-end (fewer yearly pulses that could slow down performance, less chaining of events to accomplish tasks, &c.)

**Comment by LT-Rascek** [comment]
New commit is rebased onto 84acd13 and provides a skeleton of how the Henotikon now works. No localization work has been done yet nor are there any graphics done either, and other events/interactions that should be implemented to call this complete are not yet.

But the associated decisions and basic events are done. Byzantine succession forces the Emperor to keep embracing the Henotikon until he chooses to repudiate (turned out to be relatively easy to do in on actions), all ecumenical rulers and clergy now either embrace or repudiate. Zealous characters always repudiate, most Byzantine vassals will embrace, and most secular rulers repudiate. This occurs _across_ Christianity, so long as the faith is ecumenical; there's no effect on non-ecumenical faiths.

If the Emperor looses Alexandria or Constantinople, or one of Jerusalem or Antioch, or the Byzantine empire no longer exists, a yearly event will clean up the Henotikon as no longer valid. This should pretty closely model what happened in WTWSMS in a CK3 context. Non-emperors can freely embrace/repudiate every 5 years if their personalities change. The event cleans things up properly, but I haven't seen it fire independently in my short tests yet.

There should still be a few events that should be written, like a repudiating realm priest pushing an embracing secular ruler to repudiate, or an embracing liege pushing a repudiating vassal to change his stance. Those could also possibly become character interactions, but I haven't tried writing those yet.

I'm still working out how ai_chance, ai_will_do, and ai_potential work (I'm still relatively new to Paradox modding), and I'm it still sure needs to be further debugged (especially the yearly event to make sure it fires within an appropriate window). But this should give you a rough Idea.

@loup99 I'm going to pause work on this for now. When you get a chance, can you do a cursory review to see if it matches what you think should happen with the Henotikon? As I said before, this isn't ready for merging yet, but I'd like to see if the approach is compatible with your vision for BP before fleshing it out more, or writing the localizations, &c.

**Comment by AvalonXD** [comment]
What happens if the WRE is still around?

**Comment by loup99** [comment]
So on the Henotikon, the aim with the edict is to heal the rift between the two churches, yet historically this failed, essentially dissatisfying both sides. The way this worked in WtWSMS in CK2 was that you had the decision, which you could enact, and it would always fail, harming moral authority and leading to the Acacian schism with the Pope after a while. Then you had the decision to end that schism by revoking the Henotikon. I agree that this railroading was unsatisfying, essentially the player and AI would always lose out, meaning this decision was better to avoid. 

So while a more dynamic version of this is welcome, with the possibility of succeeding and reconciling Monophysites at the cost of conflict with the Pope, I'm not sure both the clergy and secular landed rulers should all get a say. The pertinent audience here is the clergy, and the patriarchs of the pentarchy are inevitably those that will have the most influence. While the Pope didn't command Western Christianity in the way he would do later, the Acacian schism as such was due to the conflict between the Eastern and Western Christian Churches. If every single ruler makes their own decision, aren't we losing the nature of the conflict, which essentially involved the ERE emperor and the patriarches? Also, there is the issue of Miaphysitism not being ecumenical, meaning they aren't impacted at all.

**Comment by LT-Rascek** [comment]
> What happens if the WRE is still around?

It currently doesn't interact with the WRE as that title doesn't exist in the code. I'm open to suggestions for that.

> The way this worked in WtWSMS in CK2 was that you had the decision, which you could enact, and it would always fail, harming moral authority and leading to the Acacian schism with the Pope after a while. 

Currently, there's no way to impose the Hentikon on the whole of Ecumenical Christianity. It's a feature I'd like to deploy but its not necessary to map WtWSMS Henotikon to CK3 (which I assume should be our primary goal for v1.0). 

> If every single ruler makes their own decision, aren't we losing the nature of the conflict, which essentially involved the ERE emperor and the patriarches?

That's a fair point. The reason I included the secular rulers in those traits is to have vassal relations improved across faith lines for the ERE. It's not too much coding to restrict these traits to just clergy though; I've already included the religious and realm priests.

>  that would make the Acacian schism instantaneous, so I think in that regard the old setup was a bit slower and plausible.

Best fix for that is to chain events; the issuance doesn't have to add it initially, but have the Acian schism fire later which does and affects the realm priests/patriarchs/Byzantine Emperor.

**Pull request closed without merging**
