### PR TITLE
More error fixes

### PR DESCRIPTION
**Pull request by LT-Rascek**
Attempting to fix the latest CTD. I'm ignoring localization errors right now as they should not be causing this type of error.
I'm thinking it might have something to do with magyar_pagan not existing wrt default events, but I'm not sure. I'm just tackling the easiest issues first, given lack of time.

### CODE REVIEW

**Comment by LT-Rascek** [comment]
I've compared vanilla v1.3.1 and V1.4.2 to see what files differ between the two versions to narrow down the CTD. It includes *all* the files (including GUI, binaries, localizations, and the like), but I think the cause is probably somewhere in the /common/ folder (173 files differ). For the sake of completeness, I've left the entire difference list in the attached text file.
[diff_lists.txt](https://github.com/loup99/BP/files/6820302/diff_lists.txt)

**Comment by loup99** [comment]
I tried to add magyar_pagan and it did not make any difference with regards to the crashes, for your information.

**Comment by loup99** [comment]
Given that I have merged the common folder and done several comparisons (I can make mistakes, although then the review of the merge is rather quick) it is either an issue with an error that suddenly causes a crash which did not happen before or with a file which changed between versions we do not include but should.

**Comment by LT-Rascek** [comment]
I spent a bit more time on the CTD, this time I took the error log before the crash (i.e., in the bookmark string; pre_error.log), the error log after the crash (i.e., after trying to choose a character; error.log) and the difference between the two (post_error.log). I have a feeling that whatever the cause of the CTD is lies in post_error.log.

[pre_error.log](https://github.com/loup99/BP/files/6836787/pre_error.log)
[error.log](https://github.com/loup99/BP/files/6836788/error.log)
[post_error.log](https://github.com/loup99/BP/files/6836789/post_error.log)

**Pull request closed without merging**
